package cpi.com.hrsys.api;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.beans.factory.annotation.Qualifier;
import org.springframework.web.bind.annotation.GetMapping;
import org.springframework.web.bind.annotation.RequestMapping;
import org.springframework.web.bind.annotation.RequestParam;
import org.springframework.web.bind.annotation.ResponseBody;
import org.springframework.web.bind.annotation.RestController;

import cpi.com.hrsys.entity.User;
import cpi.com.hrsys.service.UserRepository;
import cpi.com.hrsys.util.AppConfig;


@RestController    // This means that this class is a Controller
@RequestMapping(path="/demo") // This means URL's start with /demo (after Application path)
public class ApiUser {
	@Autowired // This means to get the bean called userRepository // Which is auto-generated by Spring, we will use it to handle the data
	private UserRepository userRepository;
	@GetMapping(path="/add") // Map ONLY GET Requests
	public @ResponseBody String addNewUser (@RequestParam String name) {
		// @ResponseBody means the returned String is the response, not a view name
		// @RequestParam means it is a parameter from the GET or POST request

		System.out.println("add: " + name);
		User n = new User();
		n.setName(name);
		userRepository.save(n);
		return "Saved";
	}

	@GetMapping(path="/all")
	public @ResponseBody Iterable<User> getAllUsers() {
		System.out.println("all*********");
		// This returns a JSON or XML with the users
		return userRepository.findAll();
	}
}